name: publish
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Install SSHFS
        run: sudo apt install -y sshfs

      - name: Init SSH known_hosts
        run: |
          echo "$SSH_FINGERPRINT" >> fingerprint
          chmod 0600 fingerprint
        env:
          SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}

      - name: Prepare SSH auth key
        run: |
          echo "$SSH_KEY" > key
          chmod 0600 key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Prepare mount point
        run: mkdir mnt

      - name: Mount SSHFS
        run: sshfs "${SSH_USER}@${SSH_HOST}:${DEPLOY_FOLDER}" mnt -p "$SSH_PORT" -o IdentityFile="$(pwd)/key" -o UserKnownHostsFile="$(pwd)/fingerprint"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_FOLDER: ${{ secrets.DEPLOY_FOLDER }}

      - name: Check out the source
        run: git clone ${{ github.event.repository.clone_url }} repo

      - name: Remove old files
        run: rm -rf mnt/*

      - name: Copy new files
        run: cp -R repo/* mnt/

      - name: Unmount SSHFS
        run: fusermount -u mnt
